# Generated by Django 4.1.7 on 2023-02-26 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_organization_active_organizationapikey"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="active",
            new_name="is_active",
        ),
    ]
